### PR TITLE
623 - Create home page header story and add onto the flex gap plugin …

### PR DESCRIPTION
**Pull request by Fullstack-Lincoln**
…so that it has vertical and horizontal classes

### CODE REVIEW

**Review by philwolstenholme — CHANGES_REQUESTED** [review]
Waiting on the images being made responsive

**Comment by philwolstenholme** [comment]
@Fullstack-Lincoln on this one, what makes `field_p_hph_cta` output in a way that is styled as a button? By default Drupal will just output it as an unstyled `a`, won't it?

I think usually we'd use the

```
button_content: content.field_p_cta_link|field_value|first['#title'],
button_url: content.field_p_cta_link|field_value|first['#url']|render,
```

then something like

```
{% include "@atoms/button/button.twig" with {
        button_content: button_content,
        button_url: button_url,
        button_type: 'simple',
        attributes: create_attribute()
          .addClass([
            'u-w-full',
          ])
          .setAttribute('aria-describedby', 'cta-' ~ id)
      } only %}
```

approach to output a stylised button.

**Comment by Fullstack-Lincoln** [comment]
> @Fullstack-Lincoln on this one, what makes `field_p_hph_cta` output in a way that is styled as a button? By default Drupal will just output it as an unstyled `a`, won't it?
> 
> I think usually we'd use the
> 
> ```
> button_content: content.field_p_cta_link|field_value|first['#title'],
> button_url: content.field_p_cta_link|field_value|first['#url']|render,
> ```
> 
> then something like
> 
> ```
> {% include "@atoms/button/button.twig" with {
>         button_content: button_content,
>         button_url: button_url,
>         button_type: 'simple',
>         attributes: create_attribute()
>           .addClass([
>             'u-w-full',
>           ])
>       } only %}
> ```
> 
> approach to output a stylised button.

@philwolstenholme if i recall correctly, the field is an entity reference field referencing the button paragraph... maybe it should've been a link field? (I'll double check the spec doc)

**Comment by Fullstack-Lincoln** [comment]
> > @Fullstack-Lincoln on this one, what makes `field_p_hph_cta` output in a way that is styled as a button? By default Drupal will just output it as an unstyled `a`, won't it?
> > I think usually we'd use the
> > ```
> > button_content: content.field_p_cta_link|field_value|first['#title'],
> > button_url: content.field_p_cta_link|field_value|first['#url']|render,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then something like
> > ```
> > {% include "@atoms/button/button.twig" with {
> >         button_content: button_content,
> >         button_url: button_url,
> >         button_type: 'simple',
> >         attributes: create_attribute()
> >           .addClass([
> >             'u-w-full',
> >           ])
> >       } only %}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > approach to output a stylised button.
> 
> @philwolstenholme if i recall correctly, the field is an entity reference field referencing the button paragraph... maybe it should've been a link field? (I'll double check the spec doc)

The spec doc didn't specify the above.

**Comment by philwolstenholme** [comment]
@Fullstack-Lincoln oh yeah good point about the Button paragraph, that's what we do for the Hero header on Voyager at least, I guess we have used the same approach here.

**Review by philwolstenholme — APPROVED** [review]

**Pull request merged**
